#!/bin/bash

# --- xcode command line tools
echo "======= Checking Xcode Command Line Tools"
if ! xcode-select -p &>/dev/null; then
  echo "Triggering Xcode CLT installer..."
  xcode-select --install
  echo "Complete the install in the popup, then press Enter to continue..."
  read -r
else
  echo "Xcode CLT already installed"
fi
# ---

# --- homebrew
# NONINTERACTIVE=1 covers both the installer below and every `brew` call
# later in this script (formula installs, taps, etc.) - equivalent to apt -y.
export NONINTERACTIVE=1
echo "======= Checking Homebrew"
if ! command -v brew &>/dev/null; then
  echo "Installing Homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
  echo "Homebrew already installed"
fi
# load brew into current shell session so brew commands below work
# (shellenv only auto-runs in login shells; this script is non-login)
if [[ -x /opt/homebrew/bin/brew ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
elif [[ -x /usr/local/bin/brew ]]; then
  eval "$(/usr/local/bin/brew shellenv)"
fi
# ---

# --- oh-my-zsh
echo "======= Checking oh-my-zsh"
if [[ ! -d "$HOME/.oh-my-zsh" ]]; then
  echo "Installing oh-my-zsh..."
  # CHSH/RUNZSH=no: skip the shell-change prompt and the "drop into zsh now" step.
  # KEEP_ZSHRC=yes: don't clobber an existing ~/.zshrc; our own managed-block step below handles it.
  CHSH=no RUNZSH=no KEEP_ZSHRC=yes sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
else
  echo "oh-my-zsh already installed"
fi
# ---

# --- brew packages
# canonical formula names (nvim is an alias for neovim; brew list only matches canonical)
echo "======= Installing Homebrew packages"
BREW_PACKAGES=(bash tmux bat zoxide neovim mise fzf rtk modem-dev/tap/hunk ripgrep jq pnpm kustomize kubectx just)
for pkg in "${BREW_PACKAGES[@]}"; do
  if brew list --formula "$pkg" &>/dev/null; then
    echo "  [skip] $pkg already installed"
  else
    echo "  [install] $pkg"
    brew install "$pkg"
  fi
done
# ---

# --- uv (Python package/project manager)
# Official installer, not brew -- self-updating and matches astral's own docs.
echo "======= Checking uv"
if command -v uv &>/dev/null; then
  echo "uv already installed at $(command -v uv)"
else
  echo "Installing uv..."
  curl -LsSf https://astral.sh/uv/install.sh | sh
fi
# ---

# --- claude code
# Use the official installer (self-updating ~/.local/share/claude/versions/*)
# instead of a brew cask, which lags behind upstream.
echo "======= Checking Claude Code"
if command -v claude &>/dev/null; then
  echo "Claude Code already installed at $(command -v claude)"
else
  echo "Installing Claude Code via official installer..."
  curl -fsSL https://claude.ai/install.sh | bash
fi
# ---

# --- claude code skills
# Wire up brew-installed tool skills under ~/.claude/skills/. Symlink against
# /opt/homebrew/opt/<formula>/... (version-stable; survives brew upgrade).
echo "======= Configuring Claude Code skills"
HUNK_SKILL_TARGET="/opt/homebrew/opt/hunk/libexec/skills/hunk-review/SKILL.md"
HUNK_SKILL_LINK="$HOME/.claude/skills/hunk-review/SKILL.md"
if [[ -f "$HUNK_SKILL_TARGET" ]]; then
  mkdir -p "$(dirname "$HUNK_SKILL_LINK")"
  ln -sf "$HUNK_SKILL_TARGET" "$HUNK_SKILL_LINK"
  echo "Linked hunk-review -> $HUNK_SKILL_TARGET"
else
  echo "hunk skill not found at $HUNK_SKILL_TARGET, skipping"
fi
# ---

# --- claude code user config
# CLAUDE.md @-imports RTK.md; RTK.md is generated by `rtk init -g` (requires brew rtk above)
echo "======= Configuring Claude Code user rules"
mkdir -p "$HOME/.claude"
cp CLAUDE.md "$HOME/.claude/CLAUDE.md"
rtk init -g
# ---

# --- ssh key
echo "======= Checking SSH key"
SSH_KEY="$HOME/.ssh/id_ed25519"
if [[ -f "$SSH_KEY" ]]; then
  echo "SSH key already exists at $SSH_KEY"
else
  mkdir -p "$HOME/.ssh"
  chmod 700 "$HOME/.ssh"
  # source the key comment from the dotfile gitconfig (this script may run before ~/.gitconfig is deployed)
  KEY_COMMENT="$(git config --file gitconfig user.email 2>/dev/null || echo "$(whoami)@$(hostname)")"
  ssh-keygen -t ed25519 -f "$SSH_KEY" -C "$KEY_COMMENT" -N ""
  echo "Generated $SSH_KEY"
fi
# ---

# --- ssh allowed_signers (local git signature verification)
echo "======= Configuring ssh allowed_signers"
ALLOWED_SIGNERS="$HOME/.ssh/allowed_signers"
PUB_KEY="$HOME/.ssh/id_ed25519.pub"
if [[ -f "$ALLOWED_SIGNERS" ]]; then
  echo "$ALLOWED_SIGNERS already exists, skipping"
elif [[ -f "$PUB_KEY" ]]; then
  GIT_EMAIL="$(git config --file gitconfig user.email)"
  # format: <principal> namespaces="<list>" <key_type> <key_data>
  # namespaces="git" restricts trust to commit signing only
  KEY_FIELDS="$(awk '{print $1, $2}' "$PUB_KEY")"
  echo "$GIT_EMAIL namespaces=\"git\" $KEY_FIELDS" > "$ALLOWED_SIGNERS"
  echo "Wrote $ALLOWED_SIGNERS"
else
  echo "$PUB_KEY not found, skipping allowed_signers"
fi
# ---

# --- dependency checks
echo "======= Checking dependencies"

if ! command -v zsh &>/dev/null; then
  echo "ERROR: zsh is not installed"
  exit 1
fi

if ! command -v tmux &>/dev/null; then
  echo "ERROR: tmux is not installed"
  exit 1
fi

if ! command -v bash &>/dev/null; then
  echo "ERROR: bash is not installed"
  exit 1
fi

BASH_VERSION_INSTALLED=$(bash --version | head -1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)
BASH_MAJOR=${BASH_VERSION_INSTALLED%%.*}
BASH_MINOR=$(echo "$BASH_VERSION_INSTALLED" | cut -d. -f2)
if (( BASH_MAJOR < 5 )) || (( BASH_MAJOR == 5 && BASH_MINOR < 3 )); then
  echo "ERROR: bash >= 5.3 required, found $BASH_VERSION_INSTALLED"
  exit 1
fi

echo "All dependencies found"
# ---

# --- mise runtimes
# Editor tooling needs runtimes managed by mise:
#  - stable Python 3: debugpy powers nvim-dap; pudb is the standalone TUI debugger
#  - Node 22 LTS for coc.nvim (Node 25 breaks coc-pyright's Web Storage localStorage)
# Put mise shims on PATH so the headless nvim PlugInstall below resolves python3/node.
echo "======= Installing mise runtimes"
eval "$(mise activate bash --shims)"
mise use -g python@3.13
mise use -g node@22
mise exec python@3.13 -- python -m pip install --upgrade pip debugpy pudb
# ---

# --- mnemo (personal AI memory CLI)
# Install from the latest GitHub release tarball, not a plain clone+build:
# release.yml's publish-cli job stamps the real Auth0 domain/audience/client
# id into cli/src/defaults.ts before building. A local build leaves those
# blank (they're only set as GitHub Actions repo Variables), which breaks
# `mnemo login` with a fetch error against an empty https:// URL.
echo "======= Installing mnemo CLI"
if command -v mnemo &>/dev/null; then
  echo "mnemo already installed: $(mnemo --version 2>&1 | head -1)"
else
  MNEMO_TARBALL_URL=$(curl -fsSL https://api.github.com/repos/tiagodeoliveira/mnemo/releases/latest \
    | grep -o '"browser_download_url": *"[^"]*mnemo-cli-[^"]*\.tgz"' \
    | head -1 | cut -d'"' -f4)
  if [[ -z "$MNEMO_TARBALL_URL" ]]; then
    echo "ERROR: no mnemo-cli release tarball found on GitHub; cut a release (tag v*) first"
    exit 1
  fi
  MNEMO_TGZ="$(mktemp -t mnemo-cli).tgz"
  curl -fsSL "$MNEMO_TARBALL_URL" -o "$MNEMO_TGZ"
  mise exec node@22 -- npm install -g "$MNEMO_TGZ"
  rm -f "$MNEMO_TGZ"
fi
# ---

# --- auris (personal meeting-transcription CLI)
# Same release-tarball approach as mnemo above: release.yml stamps the real
# Auth0 domain/audience/client id into the build before publishing, so a
# local build or plain npm install leaves those blank and breaks `auris login`.
echo "======= Installing auris CLI"
if command -v auris &>/dev/null; then
  echo "auris already installed at $(command -v auris)"
else
  AURIS_TARBALL_URL=$(curl -fsSL https://api.github.com/repos/tiagodeoliveira/auris/releases/latest \
    | grep -o '"browser_download_url": *"[^"]*auris-cli-[^"]*\.tgz"' \
    | head -1 | cut -d'"' -f4)
  if [[ -z "$AURIS_TARBALL_URL" ]]; then
    echo "ERROR: no auris-cli release tarball found on GitHub; cut a release (tag v*) first"
    exit 1
  fi
  AURIS_TGZ="$(mktemp -t auris-cli).tgz"
  curl -fsSL "$AURIS_TARBALL_URL" -o "$AURIS_TGZ"
  mise exec node@22 -- npm install -g "$AURIS_TGZ"
  rm -f "$AURIS_TGZ"
fi
# ---

# --- claude code mcp registration (mnemo + auris)
# Wire up the personal memory/meeting MCP servers now that both CLIs and
# Claude Code itself are installed. -s user scope makes them available in
# every project, matching how CLAUDE.md documents them as always-on.
echo "======= Registering mnemo and auris MCP servers"
MISE_NODE_BIN="$HOME/.local/share/mise/installs/node/22/bin"
if claude mcp get mnemo &>/dev/null; then
  echo "mnemo MCP already registered"
else
  claude mcp add -s user mnemo -- node "$MISE_NODE_BIN/mnemo-mcp"
fi
if claude mcp get auris &>/dev/null; then
  echo "auris MCP already registered"
else
  claude mcp add -s user auris -- node "$MISE_NODE_BIN/auris-mcp"
fi
# ---

# --- agentoast (menu bar toast for Claude Code Stop/permission-prompt events)
echo "======= Checking agentoast"
if brew list --cask agentoast &>/dev/null; then
  echo "agentoast already installed"
else
  echo "Installing agentoast..."
  brew install --cask shuntaka9576/tap/agentoast
fi

# Merge in just the Stop/Notification hooks -- settings.json also carries
# rtk's/mnemo's hooks and unrelated personal settings (model, plugins, theme),
# so this must not overwrite the file wholesale.
CLAUDE_SETTINGS="$HOME/.claude/settings.json"
mkdir -p "$(dirname "$CLAUDE_SETTINGS")"
[[ -f "$CLAUDE_SETTINGS" ]] || echo '{}' > "$CLAUDE_SETTINGS"
for event in Stop Notification; do
  HAS_HOOK=$(jq --arg ev "$event" '(.hooks[$ev] // []) | any(.hooks[]?.command == "agentoast hook claude")' "$CLAUDE_SETTINGS")
  if [[ "$HAS_HOOK" != "true" ]]; then
    jq --arg ev "$event" \
      '.hooks[$ev] = ((.hooks[$ev] // []) + [{"matcher": "", "hooks": [{"type": "command", "command": "agentoast hook claude"}]}])' \
      "$CLAUDE_SETTINGS" > "$CLAUDE_SETTINGS.tmp" && mv "$CLAUDE_SETTINGS.tmp" "$CLAUDE_SETTINGS"
    echo "Added $event hook for agentoast"
  else
    echo "$event hook for agentoast already present"
  fi
done
# ---

# --- nvim
echo "======= Configuring nvim"
mkdir -p $HOME/.config/nvim
cp init.lua $HOME/.config/nvim
cp coc-settings.json $HOME/.config/nvim  # pins pyright to the mise python (sees our deps)

if [[ ! -d "$HOME/.config/nvim/autoload" ]]; then
  curl -fLo $HOME/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

nvim +silent +PlugUpgrade +PlugUpdate +PlugInstall +PlugClean +qall
# ---

# --- tmux
echo "======= Configuring tmux"
if [[ ! -d "$HOME/.tmux/plugins/tpm" ]]; then
  mkdir -p $HOME/.tmux/plugins
  git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm
fi

cp tmux.conf $HOME/.tmux.conf

# tpm's install_plugins reads @plugin entries off a running tmux server, so
# drive it from a throwaway detached session instead of a manual prefix + I.
echo "Installing tmux plugins via tpm..."
tmux start-server
tmux new-session -d -s __dotfiles_setup
tmux source-file "$HOME/.tmux.conf"
"$HOME/.tmux/plugins/tpm/bin/install_plugins"
tmux kill-session -t __dotfiles_setup
# ---

# --- ghostty
echo "======= Configuring ghostty"
if [[ -d "$HOME/Library/Application Support/com.mitchellh.ghostty" ]]; then
  cp ghostty_config "$HOME/Library/Application Support/com.mitchellh.ghostty/config"
else
  echo "Ghostty config directory not found, skipping"
fi
# ---

# --- zsh
# Managed-block model: replace just the marked block in ~/.zshrc; leave the
# rest (machine-specific PATH, dev tool injections, etc.) untouched.
echo "======= Configuring zsh"
ZSHRC="$HOME/.zshrc"
ZSHRC_START="# >>> dotfiles managed >>>"
ZSHRC_END="# <<< dotfiles managed <<<"

if [[ ! -f zshrc ]]; then
  echo "zshrc not found in repo, skipping"
elif [[ -f "$ZSHRC" ]] && grep -qF "$ZSHRC_START" "$ZSHRC"; then
  echo "Updating managed block in $ZSHRC"
  # Replace content between markers in place, preserving block position
  # and everything outside the markers.
  awk -v start="$ZSHRC_START" -v end="$ZSHRC_END" -v file="zshrc" '
    $0 == start {
      print start
      while ((getline line < file) > 0) print line
      close(file)
      print end
      skip = 1
      next
    }
    $0 == end { skip = 0; next }
    !skip { print }
  ' "$ZSHRC" > "$ZSHRC.tmp" && mv "$ZSHRC.tmp" "$ZSHRC"
else
  echo "Appending managed block to $ZSHRC"
  {
    [[ -s "$ZSHRC" ]] && echo ""
    echo "$ZSHRC_START"
    cat zshrc
    echo "$ZSHRC_END"
  } >> "$ZSHRC"
fi
# ---

# --- git
echo "======= Configuring git"
cp gitconfig $HOME/.gitconfig
cp gitignore_global $HOME/.gitignore_global
# ---

# --- manual follow-ups
# Surface the work the script cannot do for the user (interactive auth, etc.)
cat <<'EOF'

======= Setup done. Manual steps left:

  1. mnemo login          # Auth0 device flow for the memory CLI
  2. auris login          # Auth0 device flow for the meeting CLI
  3. claude               # then /login to authenticate Claude Code
  4. Add SSH key to GitHub: pbcopy < ~/.ssh/id_ed25519.pub
                          # then paste at https://github.com/settings/keys

EOF
# ---
