set -g mouse on
set -g mode-keys vi
set -g allow-passthrough on
set -g history-limit 100000

set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

set-option -sg escape-time 10
set-option -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ',xterm-kitty:cnorm=\E[?12h\E[?25h'

# Vi copy mode bindings
bind-key -T copy-mode-vi 'v' send-keys -X begin-selection
bind-key -T copy-mode-vi 'V' send-keys -X select-line
bind-key -T copy-mode-vi 'C-v' send-keys -X rectangle-toggle
bind-key -T copy-mode-vi 'y' send-keys -X copy-selection-and-cancel

# For macOS clipboard integration
bind-key -T copy-mode-vi 'y' send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"

# New window with current path
bind c new-window -c "#{pane_current_path}"

unbind '"'
unbind %

# TokyoNight theme
set -g @tokyo-night-tmux_theme night    # storm | day | default to 'night'
set -g @tokyo-night-tmux_transparent 1  # 1 or 0
set -g @tokyo-night-tmux_window_id_style digital
set -g @tokyo-night-tmux_pane_id_style hsquare
set -g @tokyo-night-tmux_zoom_id_style dsquare
set -g @tokyo-night-tmux_terminal_icon 
set -g @tokyo-night-tmux_active_terminal_icon 
set -g @tokyo-night-tmux_show_music 0
set -g @tokyo-night-tmux_show_netspeed 0
set -g @tokyo-night-tmux_window_tidy_icons 0
set -g @tokyo-night-tmux_show_path 1
set -g @tokyo-night-tmux_path_format relative # 'relative' or 'full'
set -g @tokyo-night-tmux_show_hostname 1

# ssh split
set-option -g @ssh-split-keep-cwd "true"
set-option -g @ssh-split-keep-remote-cwd "true"
set-option -g @ssh-split-fail "false"
set-option -g @ssh-split-no-env "false"
set-option -g @ssh-split-no-shell "false"
set-option -g @ssh-split-strip-cmd "true"
set-option -g @ssh-split-verbose "true"
set-option -g @ssh-split-debug "true"
set-option -g @ssh-split-h-key "|"
set-option -g @ssh-split-v-key "_"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'janoamaral/tokyo-night-tmux'
set -g @plugin 'pschmitt/tmux-ssh-split'

run '~/.tmux/plugins/tpm/tpm'
